---
title: "Presentation"
author: "Gabriel Aguirre"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(tidyr)
```


# Data
```{r, echo=FALSE}
# add column to indicate streaming platform

netflix = read_csv("netflix_titles.csv", show_col_types = FALSE)
hbo = read_csv("hbo_titles.csv", show_col_types = FALSE)
amazon = read_csv("amazon_titles.csv", show_col_types = FALSE)
disney = read_csv("disney_titles.csv", show_col_types = FALSE)
apple = read_csv("apple_titles.csv", show_col_types = FALSE)

# remove unwanted data 'id', and 'imdb_id'

netflix = netflix %>% subset(select = -c(id, imdb_id))
amazon = amazon %>% subset(select = -c(id, imdb_id))
apple = apple %>% subset(select = -c(id, imdb_id))
hbo = hbo %>% subset(select = -c(id, imdb_id))
disney = disney %>% subset(select = -c(id, imdb_id))

# add column to show show streaming platforms and reorganize columns

netflix = netflix %>% mutate(platform = 'Netflix') %>% select(platform, everything())
disney = disney %>% mutate(platform = 'Disney') %>% select(platform, everything())
hbo = hbo %>% mutate(platform = 'HBO Max') %>% select(platform, everything())
apple = apple %>% mutate(platform = 'Apple TV') %>% select(platform, everything())
amazon = amazon %>% mutate(platform = 'Amazon') %>% select(platform, everything())  
```
# combine
 - all data sets as one : all_titles
 - date for just movies : all_movies
 - data for just shows  : all_shows
```{r, echo=FALSE}

all_titles = full_join(netflix, amazon) %>% full_join(apple) %>% full_join(disney) %>% full_join(hbo)

all_movies = all_titles %>% filter(type == 'MOVIE')

all_shows = all_titles %>% filter(type == 'SHOW')
```


#movies and shows by %
```{r pressure, echo=FALSE}
#shows the ratio of movies to shows for each separate platform in one table
all_totals = full_join(disney %>% group_by(platform, type) %>% summarise(percent = 100 * n() / nrow(disney), total = n(), .groups = 'drop'),
                       netflix %>% group_by(platform, type) %>% summarise(percent = 100 * n() / nrow(netflix), total = n(), .groups = 'drop')) %>% 
                       full_join(hbo %>% group_by(platform,type) %>% summarise(percent = 100 * n() / nrow(hbo), total = n(), .groups = 'drop')) %>% 
                       full_join(amazon %>% group_by(platform,type) %>% summarise(percent = 100 * n() / nrow(amazon), total = n(), .groups = 'drop')) %>% 
                       full_join(apple %>% group_by(platform,type) %>% summarise(percent = 100 * n() / nrow(apple), total = n(), .groups = 'drop'))
#table
all_totals  

#graph
all_totals %>% 
  ggplot(aes(platform,percent, fill = type)) + geom_bar(stat ="identity", position = "dodge") + geom_text(aes(label = paste(round(percent), "%")), vjust = -0.5, color = "black", size = 3, position=position_dodge(1))

all_titles %>% 
  group_by(type) %>% summarise(percent = paste(round(100 * n() / nrow(all_titles), digits = 2),"%"), total = n()) %>% 
  ggplot(aes(type,percent, fill = type)) + geom_bar(stat ="identity", position = "dodge") + geom_text(aes(label = percent), vjust = -0.5, color = "black", size = 3, position=position_dodge(1))
```


#imdb vs tmdb
```{r}
#imdb vs votes
all_titles %>% ggplot() + aes(imdb_score ,imdb_votes, color = type) + geom_point(na.rm = T, position = 'jitter') + facet_wrap(~ platform)

#tmdb vs popularity
all_titles %>% ggplot() + aes(tmdb_score ,tmdb_popularity, color = type) + geom_point(na.rm = T, position = 'jitter') + facet_wrap(~ platform)

#imdb vs tmdb
all_titles %>% ggplot() + aes(tmdb_score ,imdb_score , color = type) + geom_density_2d(na.rm = T) + facet_wrap(~ platform)

```
#imdb vs tmdb
 - same info but with HISTOGRAMS!!!
```{r}
#imdb
all_titles %>% filter(imdb_score > 5) %>% ggplot() + aes(imdb_score, fill = type) + geom_histogram(binwidth = 1/3)+facet_wrap(~ platform)
all_titles %>% ggplot() + aes(imdb_score, fill = 'blue') + geom_histogram()+facet_wrap(~ type)

#tmbd
all_titles %>% filter(tmdb_score > 5) %>% ggplot() + aes(tmdb_score, fill = type) + geom_histogram(binwidth = 1/3)+facet_wrap(~ platform)
all_titles %>% ggplot() + aes(tmdb_score, fill = 'red') + geom_histogram()+facet_wrap(~ type)
```


```{r}
all_titles %>% group_by(release_year) %>% summarise(count = n())

all_titles = all_titles %>% mutate(decade = paste(floor(release_year/10)*10))
all_titles %>% group_by(decade) %>% summarise(count = n())
nw = all_titles %>% filter(age_certification != is.na(age_certification))%>%group_by(age_certification) %>% summarise(count = n())
nw %>% mutate(description <- c("General Audience","No One 17 and Under Admitted","Parental Guidance Suggested","Parents Strongly Cautioned","Restricted", "Parents Strongly Cautioned","General Audience", "Mature Audience Only", "Parental Guidance Suggested", "All Children", "Directed to older children", "Directed to older children"
))

```